"""empty message

Revision ID: e368a23a20a9
Revises: 2d5a73df0014
Create Date: 2025-03-13 17:48:41.034948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e368a23a20a9'
down_revision = '2d5a73df0014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
